import TopBar from './topBar';
import { topBarConfigType } from "../../services/common";
import { Container, Box, Center, Image, Flex, Text } from "@chakra-ui/react";
import SQL from '../../assets/images/sql.svg';
import Table from '../../assets/images/table.svg';
import DBT from '../../assets/images/dbt.svg';

const topBarConfig: topBarConfigType = {
    heading: 'Select a modeling method',
    button_text: 'Exit',
    Step: 2,
}

const methods = [{
    image: SQL,
    heading: 'SQL Query',
    sub_heading: "Filter, transform, and join your data using a SQL query",
},
{
    image: Table,
    heading: 'Table Selector',
    sub_heading: "Read all rows from an existing table or view in your database",
},
{
    image: DBT,
    heading: 'dbt Model',
    sub_heading: "Use a table or materiaized view generated by dbt",
}]


const Method = (): JSX.Element => {

    return (
        <Container className='custom_main_model_form' minW={'100%'}>
            <Flex width={'100%'} maxW={'75%'} flexDirection={'column'}>
                <TopBar topBarConfig={topBarConfig} />
                <Flex justifyContent={'space-between'}
                    bg="bg.surface"
                    borderRadius={{ base: 'none', md: 'lg' }}
                >
                    {methods.map((item) => (
                        <Box cursor={'pointer'} borderRadius={'5px'} borderColor={'#EAECF0'} p="5" maxW="310px" borderWidth="1px">
                            <Image borderRadius="md" src={item.image} />
                            <Text color={'dark_gray'} mt={2} fontSize="18px" fontWeight="semibold" lineHeight="short">
                                {item.heading}
                            </Text>
                            <Text fontSize={'sm'} color={'#475467'} mt={2}>{item.sub_heading}</Text>
                        </Box>
                    ))}

                </Flex>
            </Flex>

        </Container>
    )
}
export default Method;






